---
title: "Homogeneous poisson process"
author: "Gustavo Almeida Silva"
date: "23/07/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Simulating the arrival time in a homogenus poisson  process
```{r}
poi.process <- function(lambda,n){
  
  # initialize vector of total wait time for the arrival of each event:
  s<-numeric(n+1)
  # set S_0 = 0
  s[1] <-0
  # generate vector of iid Exp random variables:
  x <-replicate(n,rexp(1,lambda))
  # assign wait time to vector s in for loop:
  for (k in 1:n){
    
    s[k+1] <-sum(x[1:k])
    
  }
  # return vector of wait time
  return(s)
  
}

```

## Ploting the simulation
```{r}
poi_plot=function(data,lambda,n){
plot(stepfun(0:(n-1), data), 
     do.points = TRUE,
     pch = 16,
     col.points = "red",
     verticals = FALSE,
     main = paste('Realization of a Poisson process with lambda =',lambda),
     xlab = 'Time of arrival',
     ylab = 'Number of arrivals')
}
```

## Functions tests
```{r}
n=sample(c(1:100),1)
lambda=sample(c(1:5),1)
paste('Let n:',n,'and lambda:',lambda)
data=poi.process(lambda,n)
poi_plot(data,lambda,n)
```

